### ISSUE TITLE
Implementing checksum

### ISSUE THREAD

**Issue by NiKiZe** [williballenthin/python-registry#40]
Have there been any thoughts how checksum should be implemented.
Or more correctly how inconsistencies with sequence number or checksum should be handled / reported?

Code below works, but leaves a few things to be desired in regards to feedback.
```diff
diff --git a/Registry/RegistryParse.py b/Registry/RegistryParse.py
index e5e9a56..d2a0b9f 100644
--- a/Registry/RegistryParse.py
+++ b/Registry/RegistryParse.py
@@ -243,9 +243,21 @@ class REGFBlock(RegistryBlock):
 
         if _seq1 != _seq2:
             # the registry was not synchronized
+            print("Sequence counters is out of sync %s %s" % (_seq1, _seq2))
             pass
 
-        # TODO: compute checksum and check
+        # compute checksum and check
+        _ssum = self.stored_checksum()
+        _csum = self.calculate_checksum()
+        if _ssum != _csum:
+            print("Checksum 0x%x do not match calculated 0x%x" % (_ssum, _csum))
+            pass
 
     def major_version(self):
         """
@@ -273,6 +291,27 @@ class REGFBlock(RegistryBlock):
         """
         return self.unpack_dword(0x28)
 
+    def stored_checksum(self):
+        """
+        Get the stored checksum in file.
+        """
+        return self.unpack_dword(0x1FC)
+
+    def calculate_checksum(self):
+        """
+        checksum is calculated over the first 0x200 bytes
+        XOR of all D-Words from 0x00000000 to 0x000001FB
+        """
+        csum = 0
+        idx = 0x0
+        while idx <= 0x1FB: # 0x1FC includes the checksum value and should result in zero
+            _csum = self.unpack_dword(idx)
+            #print("add 0x%08x to 0x%8x at 0x%8x gives 0x%8x" % (_csum, csum, idx, csum ^ _csum))
+            csum ^= _csum
+            idx += 0x4
+
+        return csum
+
     def first_key(self):
         first_hbin = next(self.hbins())
 
```

**Comment by williballenthin** [comment]
This is good. To be honest, when I was doing the initial dev, the documentation I had didn't describe the checksum, so I didn't implement it. Your implementation is clear, and I'd be happy to merge it. 

I think we'd better not error during construction, since it might be desirable to do a best effort parse of the hive. Instead, I recommend a `validate_checksum()` method that returns `True/False` if the match/conflict. Then, probably add a `validate()` method that both calls `validate_checksum()` and compares the sequence numbers. Would you be willing to submit a PR with these changes?

Thanks again for reporting this issue and suggesting a fix!

**Comment by NiKiZe** [comment]
Will implement and create a PR for
`validate()` that calls `validate_checksum()` and `validate_sequence()`
it will also expose the appropriate fields
